# Generated by Django 5.2.5 on 2025-08-13 10:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('OPEN', '모집중'), ('CLOSED', '종료/중단')], db_index=True, default='OPEN', max_length=10)),
                ('category', models.CharField(choices=[('AD_COPY', '광고 문구'), ('CARD_NEWS', '카드 뉴스'), ('REELS', '릴스'), ('INTERIOR', '인테리어 제안'), ('MARKETING', '마케팅(기획)')], db_index=True, max_length=20)),
                ('saved_count', models.IntegerField(default=0)),
                ('requirement', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='accounts.profile')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='accounts.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Saved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='inquiries.request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='accounts.profile')),
            ],
            options={
                'unique_together': {('user', 'request')},
            },
        ),
    ]
