# Generated by Django 5.2.5 on 2025-08-15 14:18

import inquiries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='store',
        ),
        migrations.AddField(
            model_name='request',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=inquiries.models.request_image_path),
        ),
        migrations.AddField(
            model_name='request',
            name='url',
            field=models.URLField(default='https://example.com'),
        ),
    ]
