# Generated by Django 5.2.5 on 2025-08-15 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiries", "0002_remove_request_store_request_image_request_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="request",
            name="requirement",
        ),
        migrations.AlterField(
            model_name="request",
            name="category",
            field=models.CharField(
                choices=[
                    ("PROMO_VIDEO", "홍보영상"),
                    ("POSTER_FLYER", "포스터·전단"),
                    ("SNS_IMAGE", "SNS 이미지"),
                    ("INTERIOR_PROPOSAL", "인테리어 제안"),
                    ("PROMOTION_PLANNING", "홍보기획"),
                    ("AD_COPY", "광고문구"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "모집중"),
                    ("ONGOING", "진행중"),
                    ("CLOSED", "종료/중단"),
                ],
                db_index=True,
                default="OPEN",
                max_length=10,
            ),
        ),
    ]
