# Generated by Django 5.2.5 on 2025-08-15 22:50

import inquiries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inquiries",
            "0003_remove_request_requirement_alter_request_category_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="request",
            name="store_name",
            field=models.CharField(db_index=True, default="가게명", max_length=50),
        ),
        migrations.AddField(
            model_name="request",
            name="title",
            field=models.CharField(default="제목", max_length=16),
        ),
        migrations.AlterField(
            model_name="request",
            name="category",
            field=models.CharField(
                choices=[
                    ("PROMO_VIDEO", "홍보영상"),
                    ("POSTER_FLYER", "포스터·전단"),
                    ("SNS_IMAGE", "SNS 이미지"),
                    ("INTERIOR_PROPOSAL", "인테리어 제안"),
                    ("PROMOTION_PLANNING", "홍보기획"),
                    ("AD_COPY", "광고문구"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="image",
            field=models.ImageField(
                default="", upload_to=inquiries.models.request_image_path
            ),
        ),
    ]
