# Generated by Django 5.2.5 on 2025-08-16 14:58

import django.utils.timezone
import inquiries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0004_request_content_request_store_name_request_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_name', models.CharField(db_index=True, default='가게명', max_length=50)),
                ('image', models.ImageField(default='', upload_to=inquiries.models.ai_request_image_path)),
                ('url', models.URLField(default='https://example.com')),
                ('category', models.CharField(choices=[('PROMO_VIDEO', '홍보영상'), ('POSTER_FLYER', '포스터·전단'), ('SNS_IMAGE', 'SNS 이미지'), ('INTERIOR_PROPOSAL', '인테리어 제안'), ('PROMOTION_PLANNING', '홍보기획'), ('AD_COPY', '광고문구')], db_index=True, max_length=30)),
                ('title', models.CharField(default='제목', max_length=16)),
                ('content', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', '진행중'), ('DONE', '완료')], db_index=True, default='IN_PROGRESS', max_length=15)),
                ('saved_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
