# Generated by Django 5.2.5 on 2025-08-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0005_airequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airequest',
            name='status',
            field=models.CharField(choices=[('OPEN', '모집중'), ('ONGOING', '진행중'), ('CLOSED', '종료/중단')], db_index=True, default='OPEN', max_length=15),
        ),
    ]
