# Generated by Django 5.2.5 on 2025-08-20 17:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_profile_user"),
        ("inquiries", "0006_alter_airequest_status"),
        ("outcomes", "0002_remove_outcome_content_outcomefile_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NopoFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "overall_satisfaction",
                    models.CharField(
                        choices=[
                            ("VERY_GOOD", "매우 만족"),
                            ("GOOD", "만족"),
                            ("NORMAL", "보통"),
                            ("BAD", "아쉬움"),
                            ("VERY_BAD", "매우 아쉬움"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reflection_level",
                    models.CharField(
                        choices=[
                            ("VERY_REFLECTED", "매우 반영"),
                            ("SOMEWHAT", "어느정도 반영"),
                            ("NORMAL", "보통"),
                            ("LACK", "부족함"),
                            ("VERY_LACK", "매우 부족함"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "practical_use",
                    models.CharField(
                        choices=[
                            ("VERY_POSSIBLE", "매우 가능"),
                            ("POSSIBLE", "어느정도 가능"),
                            ("NORMAL", "보통"),
                            ("CONCERN", "고민됨"),
                            ("HARD", "활용 어려움"),
                        ],
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nopo_feedbacks",
                        to="accounts.profile",
                    ),
                ),
                (
                    "outcome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nopo_feedbacks",
                        to="outcomes.outcome",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("outcome", "author")},
            },
        ),
    ]
