# Generated by Django 5.2.5 on 2025-08-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiries", "0007_nopofeedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airequest",
            name="category",
            field=models.CharField(
                choices=[
                    ("POSTER_FLYER", "포스터·전단"),
                    ("SNS_IMAGE", "SNS 이미지"),
                    ("INTERIOR_PROPOSAL", "인테리어 제안"),
                    ("PROMOTION_PLANNING", "홍보기획"),
                    ("AD_COPY", "광고문구"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="category",
            field=models.CharField(
                choices=[
                    ("POSTER_FLYER", "포스터·전단"),
                    ("SNS_IMAGE", "SNS 이미지"),
                    ("INTERIOR_PROPOSAL", "인테리어 제안"),
                    ("PROMOTION_PLANNING", "홍보기획"),
                    ("AD_COPY", "광고문구"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
