# Generated by Django 5.2.5 on 2025-08-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiries", "0008_alter_airequest_category_alter_request_category"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AiRequest",
        ),
        migrations.AddField(
            model_name="request",
            name="is_ai",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
