# Generated by Django 5.2.5 on 2025-08-15 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_profile_phone_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="nickname",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_num",
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AddConstraint(
            model_name="profile",
            constraint=models.UniqueConstraint(
                fields=("phone_num", "role"), name="uniq_profile_phone_role"
            ),
        ),
    ]
