# Generated by Django 5.2.5 on 2025-08-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_nickname_alter_profile_phone_num_and_more'),
        ('inquiries', '0002_remove_request_store_request_image_request_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_authorized',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
