# Generated by Django 5.2.5 on 2025-08-13 10:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', '진행중'), ('DONE', '완료')], db_index=True, default='IN_PROGRESS', max_length=15)),
                ('plan', models.TextField(blank=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='inquiries.request')),
                ('youth', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='accounts.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
