# Generated by Django 5.2.5 on 2025-08-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_alter_mission_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', '진행중'), ('DISCARD', '포기'), ('EXPIRE', '기한만료'), ('DONE', '완료')], db_index=True, default='IN_PROGRESS', max_length=15),
        ),
    ]
