# Generated by Django 5.2.5 on 2025-08-20 02:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0003_alter_mission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='ai_model',
            field=models.CharField(default='gpt-4o-mini', max_length=50),
        ),
        migrations.AddField(
            model_name='mission',
            name='ai_plan_ver',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='mission',
            name='plan',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MissionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_no', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('reference', models.TextField()),
                ('due', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('TODO', '대기'), ('DOING', '진행중'), ('DONE', '완료'), ('EXPIRED', '기한만료')], db_index=True, default='TODO', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('feedback_count', models.PositiveIntegerField(default=0)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='missions.mission')),
            ],
            options={
                'indexes': [models.Index(fields=['mission', 'step_no'], name='missions_mi_mission_e9b07c_idx')],
                'unique_together': {('mission', 'step_no')},
            },
        ),
    ]
