# Generated by Django 5.2.5 on 2025-08-19 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0006_alter_airequest_status'),
        ('missions', '0004_mission_ai_model_mission_ai_plan_ver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='inquiries.request'),
        ),
    ]
