# Generated by Django 5.2.5 on 2025-08-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0005_alter_mission_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', '진행중'), ('EXPIRE', '기한만료'), ('DONE', '완료')], db_index=True, default='IN_PROGRESS', max_length=15),
        ),
        migrations.AlterField(
            model_name='missionstep',
            name='status',
            field=models.CharField(choices=[('TODO', '대기'), ('IN_PROGRESS', '진행중'), ('DONE', '완료'), ('EXPIRED', '기한만료')], db_index=True, default='TODO', max_length=15),
        ),
    ]
