# Generated by Django 5.2.5 on 2025-08-13 10:06

import django.db.models.deletion
import django.utils.timezone
import outcomes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nopo_pick', models.BooleanField(default=False)),
                ('content', models.TextField(blank=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='missions.mission')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outcomes_as_owner', to='accounts.profile')),
                ('youth', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outcomes_as_youth', to='accounts.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutcomeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=outcomes.models.outcome_image_path)),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='outcomes.outcome')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
