# Generated by Django 5.2.5 on 2025-08-20 02:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import outcomes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outcomes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outcome',
            name='content',
        ),
        migrations.CreateModel(
            name='OutcomeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('IMAGE', '이미지'), ('VIDEO', '비디오'), ('PDF', 'PDF')], max_length=10)),
                ('file', models.FileField(upload_to=outcomes.models.outcome_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'mp4', 'pdf'])])),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='outcomes.outcome')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='OutcomeImage',
        ),
        migrations.AddIndex(
            model_name='outcomefile',
            index=models.Index(fields=['outcome', 'order'], name='outcomes_ou_outcome_06c71a_idx'),
        ),
    ]
