# Generated by Django 5.2.5 on 2025-08-22 09:36

import django.core.validators
import outcomes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outcomes', '0002_remove_outcome_content_outcomefile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcomefile',
            name='file',
            field=models.FileField(upload_to=outcomes.models.outcome_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'txt'])]),
        ),
        migrations.AlterField(
            model_name='outcomefile',
            name='kind',
            field=models.CharField(choices=[('IMAGE', '이미지'), ('TEXT', '텍스트')], max_length=10),
        ),
    ]
